name: Test Bun Package on CI

on:
  push:
    branches: [ "main" ]

jobs:
  test_and_deploy:
    name: Test and Deploy Bun Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
      
      - name: Run tests
        run: |
          bun run test
      
      - name: Build package
        run: |
          bun run build

      - name: List files
        run: |
          echo "Package built successfully and ready for deployment"
          echo "Built files are in dist/ directory"
          ls -la .